version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/shorter-url-db?createDatabaseIfNotExist=true
      MYSQL_USER: admin
      MYSQL_PASSWORD: senha123

  mysql:
      image: mysql:8.0
      ports:
        - "3307:3306"
      restart: always
      environment:
        MYSQL_DATABASE: shorter-url-db
        MYSQL_USER: admin
        MYSQL_PASSWORD: senha123
        MYSQL_ROOT_PASSWORD: password-root
      volumes:
        - mysql-data:/var/lib/mysql
  
# Volumes
volumes:
  mysql-data:
