spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/seid_cia_db?createDatabaseIfNotExist=true
    username: root
    password: SuperM45t3r?
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    enabled: false
  flyway:
    enabled: false
  sql:
    init:
      mode: always
